### ISSUE TITLE
Logo Proposal.

### ISSUE THREAD

**Issue by regmicmahesh** [regmicmahesh/duckchatstallmaninspired#11]
What do you guys think of this?

@washbin  @CaffeineDuck 

![image](https://user-images.githubusercontent.com/64764773/153582967-b7c7fa11-a91d-4f40-9521-48dc9432dfe2.png)

**Comment by washbin** [comment]
stallman won't think highly of this censorship

**Comment by CaffeineDuck** [comment]
Approved.

**Comment by regmicmahesh** [comment]
Solved in https://github.com/regmicmahesh/duckchatstallmaninspired/commit/63f9f6a626f86064664069768ed9e713d1f431ec
